import type { Card } from "../types";

export const DECK: Card[] = [
    { name: "HEART-1", value: 1, image: "HEART-1.svg" },
    { name: "HEART-2", value: 2, image: "HEART-2.svg" },
    { name: "HEART-3", value: 3, image: "HEART-3.svg" },
    { name: "HEART-4", value: 4, image: "HEART-4.svg" },
    { name: "HEART-5", value: 5, image: "HEART-5.svg" },
    { name: "HEART-6", value: 6, image: "HEART-6.svg" },
    { name: "HEART-7", value: 7, image: "HEART-7.svg" },
    { name: "HEART-8", value: 8, image: "HEART-8.svg" },
    { name: "HEART-9", value: 9, image: "HEART-9.svg" },
    { name: "HEART-10", value: 10, image: "HEART-10.svg" },
    { name: "HEART-11-JACK", value: 11, image: "HEART-11-JACK.svg" },
    { name: "HEART-12-QUEEN", value: 12, image: "HEART-12-QUEEN.svg" },
    { name: "HEART-13-KING", value: 13, image: "HEART-13-KING.svg" },
    { name: "DIAMOND-1", value: 1, image: "DIAMOND-1.svg" },
    { name: "DIAMOND-2", value: 2, image: "DIAMOND-2.svg" },
    { name: "DIAMOND-3", value: 3, image: "DIAMOND-3.svg" },
    { name: "DIAMOND-4", value: 4, image: "DIAMOND-4.svg" },
    { name: "DIAMOND-5", value: 5, image: "DIAMOND-5.svg" },
    { name: "DIAMOND-6", value: 6, image: "DIAMOND-6.svg" },
    { name: "DIAMOND-7", value: 7, image: "DIAMOND-7.svg" },
    { name: "DIAMOND-8", value: 8, image: "DIAMOND-8.svg" },
    { name: "DIAMOND-9", value: 9, image: "DIAMOND-9.svg" },
    { name: "DIAMOND-10", value: 10, image: "DIAMOND-10.svg" },
    { name: "DIAMOND-11-JACK", value: 11, image: "DIAMOND-11-JACK.svg" },
    { name: "DIAMOND-12-QUEEN", value: 12, image: "DIAMOND-12-QUEEN.svg" },
    { name: "DIAMOND-13-KING", value: 13, image: "DIAMOND-13-KING.svg" },
    { name: "CLUB-1", value: 1, image: "CLUB-1.svg" },
    { name: "CLUB-2", value: 2, image: "CLUB-2.svg" },
    { name: "CLUB-3", value: 3, image: "CLUB-3.svg" },
    { name: "CLUB-4", value: 4, image: "CLUB-4.svg" },
    { name: "CLUB-5", value: 5, image: "CLUB-5.svg" },
    { name: "CLUB-6", value: 6, image: "CLUB-6.svg" },
    { name: "CLUB-7", value: 7, image: "CLUB-7.svg" },
    { name: "CLUB-8", value: 8, image: "CLUB-8.svg" },
    { name: "CLUB-9", value: 9, image: "CLUB-9.svg" },
    { name: "CLUB-10", value: 10, image: "CLUB-10.svg" },
    { name: "CLUB-11-JACK", value: 11, image: "CLUB-11-JACK.svg" },
    { name: "CLUB-12-QUEEN", value: 12, image: "CLUB-12-QUEEN.svg" },
    { name: "CLUB-13-KING", value: 13, image: "CLUB-13-KING.svg" },
    { name: "SPADE-1", value: 1, image: "SPADE-1.svg" },
    { name: "SPADE-2", value: 2, image: "SPADE-2.svg" },
    { name: "SPADE-3", value: 3, image: "SPADE-3.svg" },
    { name: "SPADE-4", value: 4, image: "SPADE-4.svg" },
    { name: "SPADE-5", value: 5, image: "SPADE-5.svg" },
    { name: "SPADE-6", value: 6, image: "SPADE-6.svg" },
    { name: "SPADE-7", value: 7, image: "SPADE-7.svg" },
    { name: "SPADE-8", value: 8, image: "SPADE-8.svg" },
    { name: "SPADE-9", value: 9, image: "SPADE-9.svg" },
    { name: "SPADE-10", value: 10, image: "SPADE-10.svg" },
    { name: "SPADE-11-JACK", value: 11, image: "SPADE-11-JACK.svg" },
    { name: "SPADE-12-QUEEN", value: 12, image: "SPADE-12-QUEEN.svg" },
    { name: "SPADE-13-KING", value: 13, image: "SPADE-13-KING.svg" },
];

